import {
  Briefcase,
  CheckCircle,
  Clock,
  Files,
  GraduationCap,
  ShieldCheck,
  UsersThree,
  WarningCircle,
} from "@phosphor-icons/react/dist/ssr";

export type ProjectStatus = "Por hacer" | "En curso" | "En revisión" | "Finalizado";
export type ProjectRisk = "Normal" | "Atención" | "Crítico";
export type MetricTone = "blue" | "emerald" | "orange" | "rose";

export const teams = [
  {
    id: "doe",
    name: "Departamento de Orientación",
    shortName: "DOE",
    lead: "Lic. Verón",
    leadRole: "Coordinación de convivencia y orientación",
    members: ["MR", "AL", "TJ", "NV"],
    color: "indigo",
    icon: UsersThree,
    description: "Seguimiento socioemocional, entrevistas, acuerdos de convivencia y reportes de aula.",
    activeProjects: 3,
    documents: 38,
    responseTime: "1.8 días",
  },
  {
    id: "directores",
    name: "Directores de Nivel",
    shortName: "Dirección",
    lead: "Prof. Gómez",
    leadRole: "Dirección general",
    members: ["PT", "RS", "MG"],
    color: "emerald",
    icon: ShieldCheck,
    description: "Articulación pedagógica, validaciones institucionales y coordinación entre niveles.",
    activeProjects: 2,
    documents: 44,
    responseTime: "2.4 días",
  },
  {
    id: "secretaria",
    name: "Administración y Secretaría",
    shortName: "Secretaría",
    lead: "Lucía Casares",
    leadRole: "Jefatura administrativa",
    members: ["AB", "CD", "EF", "LM", "SO"],
    color: "orange",
    icon: Files,
    description: "Legajos, documentación legal, asistencia docente y control de archivos históricos.",
    activeProjects: 4,
    documents: 126,
    responseTime: "0.9 días",
  },
  {
    id: "academico",
    name: "Coordinación Académica",
    shortName: "Académico",
    lead: "Prof. Salvatierra",
    leadRole: "Coordinación curricular",
    members: ["RC", "JM", "PV"],
    color: "blue",
    icon: GraduationCap,
    description: "Planificaciones, trayectorias, rúbricas, evaluaciones y acompañamiento docente.",
    activeProjects: 3,
    documents: 52,
    responseTime: "1.3 días",
  },
];

export const projects = [
  {
    id: "conductual-3a",
    title: "Seguimiento Conductual 3A",
    team: "DOE",
    owner: "Lic. Verón",
    status: "En curso" as ProjectStatus,
    risk: "Atención" as ProjectRisk,
    progress: 65,
    due: "08 May",
    daysLeft: 3,
    docs: 14,
    comments: 5,
    priority: "Alta",
    summary: "Carga de entrevistas, acuerdos familiares y observaciones áulicas del primer tramo.",
    nextAction: "Validar informes pendientes de matemática y lengua.",
  },
  {
    id: "articulacion",
    title: "Articulación Primaria - Secundaria",
    team: "Dirección",
    owner: "Prof. Gómez",
    status: "En revisión" as ProjectStatus,
    risk: "Crítico" as ProjectRisk,
    progress: 85,
    due: "10 May",
    daysLeft: 5,
    docs: 8,
    comments: 2,
    priority: "Alta",
    summary: "Actas, acuerdos curriculares y criterios de acompañamiento para ingresantes.",
    nextAction: "Dirección general debe aprobar el documento marco.",
  },
  {
    id: "legajos",
    title: "Auditoría Histórica de Legajos",
    team: "Secretaría",
    owner: "Lucía Casares",
    status: "En curso" as ProjectStatus,
    risk: "Normal" as ProjectRisk,
    progress: 42,
    due: "20 May",
    daysLeft: 15,
    docs: 31,
    comments: 1,
    priority: "Media",
    summary: "Normalización de archivos docentes, documentación faltante y control de vencimientos.",
    nextAction: "Cruzar documentación digital con archivo físico.",
  },
  {
    id: "esi",
    title: "Planificación Taller ESI",
    team: "Académico",
    owner: "Prof. Salvatierra",
    status: "Por hacer" as ProjectStatus,
    risk: "Normal" as ProjectRisk,
    progress: 12,
    due: "15 May",
    daysLeft: 10,
    docs: 3,
    comments: 0,
    priority: "Media",
    summary: "Definición de temarios, responsables y materiales por año para el ciclo lectivo.",
    nextAction: "Asignar docentes referentes por curso.",
  },
  {
    id: "trimestre-1",
    title: "Carga Histórica Trimestre 1",
    team: "Académico",
    owner: "Coordinación Académica",
    status: "Finalizado" as ProjectStatus,
    risk: "Normal" as ProjectRisk,
    progress: 100,
    due: "28 Abr",
    daysLeft: 0,
    docs: 48,
    comments: 7,
    priority: "Alta",
    summary: "Consolidación de actas, planillas e informes pedagógicos del primer trimestre.",
    nextAction: "Archivado y disponible para consulta.",
  },
];

export const metrics: {
  label: string;
  value: string;
  detail: string;
  trend: string;
  icon: typeof Briefcase;
  tone: MetricTone;
}[] = [
  {
    label: "Proyectos activos",
    value: "12",
    detail: "4 equipos con trabajo abierto",
    trend: "+2 esta semana",
    icon: Briefcase,
    tone: "blue",
  },
  {
    label: "Informes cargados",
    value: "142",
    detail: "86% con responsable asignado",
    trend: "+15% este mes",
    icon: CheckCircle,
    tone: "emerald",
  },
  {
    label: "Vencen pronto",
    value: "5",
    detail: "2 necesitan validación directiva",
    trend: "3 días el más urgente",
    icon: Clock,
    tone: "orange",
  },
  {
    label: "Alertas críticas",
    value: "2",
    detail: "Ambas dependen de aprobación",
    trend: "Prioridad alta",
    icon: WarningCircle,
    tone: "rose",
  },
];

export const activity = [
  {
    time: "Hoy, 11:30",
    person: "Lic. Verón",
    team: "DOE",
    title: "Informe de Observación Áulica 3A",
    detail: "Registro de clase y acuerdos de seguimiento para matemática.",
    action: "Ver documento",
    tone: "blue",
  },
  {
    time: "Hoy, 09:10",
    person: "Lucía Casares",
    team: "Secretaría",
    title: "Legajo docente actualizado",
    detail: "Se completó documentación obligatoria y quedó listo para revisión.",
    action: "Abrir legajo",
    tone: "orange",
  },
  {
    time: "Ayer, 16:45",
    person: "Prof. Gómez",
    team: "Dirección",
    title: "Acta de Articulación Primaria",
    detail: "Acta firmada por directivos de ambos niveles.",
    action: "Descargar PDF",
    tone: "emerald",
  },
  {
    time: "02 May, 09:15",
    person: "Administración",
    team: "Secretaría",
    title: "Carga histórica de inasistencias",
    detail: "Consolidación de planillas del mes de abril.",
    action: "Ver registro",
    tone: "slate",
  },
];

export const institutionalPriorities = [
  {
    title: "Aprobaciones pendientes",
    count: 4,
    description: "Documentos esperando firma o revisión directiva.",
    owner: "Dirección",
  },
  {
    title: "Seguimientos sensibles",
    count: 7,
    description: "Casos que requieren continuidad semanal y registro cuidadoso.",
    owner: "DOE",
  },
  {
    title: "Archivo histórico",
    count: 126,
    description: "Documentos digitalizados listos para consulta y auditoría.",
    owner: "Secretaría",
  },
];

export const staff = [
  { name: "Lic. Verón", initials: "V", role: "Coordinadora principal", team: "DOE", lastActivity: "Hoy, 11:30", status: "Activa" },
  { name: "Prof. Gómez", initials: "G", role: "Director general", team: "Dirección", lastActivity: "Ayer, 16:45", status: "Revisando" },
  { name: "Martín Rivas", initials: "MR", role: "Psicopedagogo", team: "DOE", lastActivity: "28 Abr", status: "Activa" },
  { name: "Lucía Casares", initials: "LC", role: "Jefa de secretaría", team: "Secretaría", lastActivity: "Hoy, 09:10", status: "Activa" },
  { name: "Prof. Salvatierra", initials: "S", role: "Coordinación curricular", team: "Académico", lastActivity: "01 May", status: "Pendiente" },
];
